#!/bin/sh
# executed at system start by exploited getsettingsvalue
# we're root, BTW

# just leave a note
touch /yes-sir-we-can-boogie

# call our script
/bin/sh /flash2/motorola.sh >/dev/null 2>&1 </dev/null &
sleep 2
exit